# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
dependency:
  name: shell
  command: echo executed before driver platform create
  env:
   DOCKER_IMAGE: ${OS_NAME:-"ubuntu:18.04"}
driver:
  name: docker
platforms:
  - name: instance-1
    image: ${DOCKER_IMAGE}
    groups:
      - master
  - name: instance-2
    image: ${DOCKER_IMAGE}
    groups:
      - slave
provisioner:
  name: ansible
  ansible_args:
    - --extra-vars=target=all
  log: True
  config_options:
    defaults:
      callback_whitelist: profile_roles,profile_tasks,timer
  playbooks:
    converge: ../../${PLAYBOOK_FILE}
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
