---
name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        docker_image: ["ubuntu:18.04", "debian:9", "centos:7", "alpine:3.6"]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Python 
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          sudo apt install docker
          python -m pip install --upgrade pip
          pip install tox
      - name: Test with tox
        run: |
          TOXENV="py{27,37}-ansible27" OS_NAME=${{ matrix.docker_image }} PLAYBOOK_FILE=playbook.yml tox -c molecule/default/tox.ini
